<?php

/**
 * 
 * 
 * PHP 5
 *
 * Sistema : Miniframework PHP OO para aplicações web.
 * 
 *
 * 
 * @copyright     Copyright 2013, Iggow
 * @author		  Iggow Developers
 * @created 	  17-01-2013
 * @link          http://www.iggow.com
 * @version       Sistema v 0.1
 * @package		  root/system/views
 */
 
 ?>

 <div id="content" class="span10">

	<div>
		<ul class="breadcrumb">
			<li>
				<a class="ajax-link" href="/sic/">Home</a><span class="divider">/</span>
			</li>
			<li>
				<a  class="ajax-link" href="#"> Erro 404 </a><span class="divider">/</span>
			</li>
		</ul>
	</div>

	<div class="row-fluid">
		<div class="span12 well">

			<h1 class="alert-error"> View não encontrada.</h1>
			<div class="clear"></div>
			<br><hr>
			<h3 class="alert-error"> Por favor crie a view correspondente no diretório app/views.</h3>
			

		</div>
	</div>
