<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />

		<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
		Remove this if you use the .htaccess -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

		<title>Iggow</title>
		<meta name="description" content="" />
		<meta name="author" content="Vagner" />

		<meta name="viewport" content="width=device-width; initial-scale=1.0" />
		<style>
			*{
				margin:0;
				padding: 0;
			}
			body{
				font-family: Tahoma;
				background: #aaaaaa;
			}
			header{
				margin: 3em;
			}
			.simple{
				width: 70%;
				margin: 0 auto;
				border: solid 1px #ccc;
				padding: 0.8em;
				border-radius: 4px;
				background: #FFFFFF;
			}
			footer{
				text-align: center;
			}
			p{
				margin: 0.4em 0 0 0;
				text-indent: 1.6em;
			}
			
		</style>
		<!-- Replace favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
		<link rel="shortcut icon" href="/favicon.ico" />
		<link rel="apple-touch-icon" href="/apple-touch-icon.png" />
	</head>

	<body>
		<div>
			<header>
				<h1>Iggow - Framework de desenvolvimento.</h1>
			</header>
			<nav>
				<div class="simple">
				
				<h1>Começe aqui</h1>
				
				<p>
					O framework desenvolvido aqui foi projetado com as tecnologias open source mais recentes
					no mercado de desenvolvimento de web sites e sistemas web.
				</p>
				<p>A àrvore de arquivos do framework é simples e intuitiva.</p>
				<p>Todos os arquivos de scripts específicos do site a ser criado estarão no diretório <u>APP</u>
				nos subdiretórios <u>CONTROLLERS</u>, <u>MODELS</u> e <u>VIEWS</u></p>
				<p>Os arquivos de formataçao e templates estarão nos diretórios de template em <u>PUBLIC/TEMPLATES/NOME_TEMPLATE</u>
					nos subdiretórios <u>IMG</u>, <u>CSS</u>,<u>JS</u>
				</p>
				<p>Métodos e classes que possam ser úteis à várias partes do site <u>HELPERS (classes ajudantes ou úteis)</u> deverão estar em <u>SYSTEM/HELPERS</u> </p>
				
				<p>ENJOY.</p>
				
				<p class="signature">Att. Vagner Leitte</p>
				</div>
			</nav>

			<div>

			</div>

			<footer>
				<p>
					&copy; Copyright  by Vagner
				</p>
			</footer>
		</div>
	</body>
</html>
